apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-ui
  namespace: gagan
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app-ui
  template:
    metadata:
      labels:
        app: todo-app-ui
    spec:
      containers:
      - name: todo-app-ui
        image: devopsinsiders/todoapp-ui-new:v2
        ports:
        - containerPort: 80
